### PR TITLE
fix `axlines` and `axspans` for axes with `upper=False`

### LINKED ISSUE #174: `axlines` and `axspans` not working when `upper=False`
As the title suggests, using the new `axlines` or `axspans` methods (introduced in #168 and as originally requested in #164) won't work when setting `upper=False` in `make_2d_axes`.

This works:
```python
from anesthetic import NestedSamples, make_2d_axes

ns = NestedSamples(root="anesthetic/tests/example_data/pc_250")

fig, axes = make_2d_axes(["x0", "x1", "x2"], upper=True)
fig, axes = ns.plot_2d(axes);
axes.axlines('x0', 0, c='k')
```
This does not work:
```python
from anesthetic import NestedSamples, make_2d_axes

ns = NestedSamples(root="anesthetic/tests/example_data/pc_250")

fig, axes = make_2d_axes(["x0", "x1", "x2"], upper=False)
fig, axes = ns.plot_2d(axes);
axes.axlines('x0', 0, c='k')
```
It fails with the error:
```python
AttributeError: 'NoneType' object has no attribute 'axhline'
```

This comes down to `upper=False` turning the unused upper triangle subplots into `None` types. Hence, they will need to be excluded from the axes used by `axlines` and `axspans`.

### PR DESCRIPTION
**Pull request by lukashergt**
For a description of the bug, see #174. This PR aims at fixing that bug.

Fixes #174 

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My code is PEP8 compliant (`flake8 anesthetic tests`)
- [x] My code contains compliant docstrings (`pydocstyle --convention=numpy anesthetic`)
- [x] New and existing unit tests pass locally with my changes (`python -m pytest`)
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by lukashergt** [comment]
Failing new tests with `upper=False` highlight the issue.

**Review by williamjameshandley — APPROVED** [review]
Makes sense to me! Well done for finding and fixing this so quickly.
