### ISSUE TITLE
`axlines` and `axspans` not working when `upper=False`

### ISSUE THREAD

**Issue by lukashergt** [williamjameshandley/anesthetic#174]
As the title suggests, using the new `axlines` or `axspans` methods (introduced in #168 and as originally requested in #164) won't work when setting `upper=False` in `make_2d_axes`.

This works:
```python
from anesthetic import NestedSamples, make_2d_axes

ns = NestedSamples(root="anesthetic/tests/example_data/pc_250")

fig, axes = make_2d_axes(["x0", "x1", "x2"], upper=True)
fig, axes = ns.plot_2d(axes);
axes.axlines('x0', 0, c='k')
```
This does not work:
```python
from anesthetic import NestedSamples, make_2d_axes

ns = NestedSamples(root="anesthetic/tests/example_data/pc_250")

fig, axes = make_2d_axes(["x0", "x1", "x2"], upper=False)
fig, axes = ns.plot_2d(axes);
axes.axlines('x0', 0, c='k')
```
It fails with the error:
```python
AttributeError: 'NoneType' object has no attribute 'axhline'
```

This comes down to `upper=False` turning the unused upper triangle subplots into `None` types. Hence, they will need to be excluded from the axes used by `axlines` and `axspans`.
